name: Release

on:
  push:
    branches:
      - master
      - v0.15.x

jobs:
  release-please:
    name: Create Release
    outputs:
      release-pr: ${{ steps.release.outputs.pr }}
      tag-name: ${{ steps.release.outputs.tag_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.ACVM_RELEASE_TOKEN }}
          command: manifest
          last-release-sha: bc9c0bc82bee32151e269fead968d6de99daf995
